{% set version = "1.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ctrdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ctrdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ctrdata/ctrdata_{{ version }}.tar.gz
  sha256: 55437f9cede1246392317ee4f51b120ee13597f5a56d0236c57c766aff61c58e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-clipr
    - r-curl >=5.0
    - r-dplyr
    - r-httr
    - r-jqr
    - r-jsonlite
    - r-lubridate
    - r-nodbi >=0.9.0
    - r-rvest
    - r-stringi
    - r-xml2
  run:
    - r-base
    - r-clipr
    - r-curl >=5.0
    - r-dplyr
    - r-httr
    - r-jqr
    - r-jsonlite
    - r-lubridate
    - r-nodbi >=0.9.0
    - r-rvest
    - r-stringi
    - r-xml2

test:
  commands:
    - $R -e "library('ctrdata')"           # [not win]
    - "\"%R%\" -e \"library('ctrdata')\""  # [win]

about:
  home: https://cran.r-project.org/package=ctrdata
  license: MIT
  summary: A system for querying, retrieving and analyzing protocol- and results-related information on clinical trials from three public registers, the 'European Union Clinical Trials Register' ('EUCTR', <https://www.clinicaltrialsregister.eu/>), 'ClinicalTrials.gov' ('CTGOV', <https://clinicaltrials.gov/>), the 'ISRCTN'
    (<http://www.isrctn.com/>) and the 'European Union Clinical Trials Information System' ('CTIS', <https://euclinicaltrials.eu/>). Trial information is downloaded, converted and stored in a database ('PostgreSQL', 'SQLite', 'DuckDB' or 'MongoDB'; via package 'nodbi'). Functions are included to identify deduplicated records,
    to easily find and extract variables (fields) of interest even from complex nesting as used by the registers, and to update previous queries. The package can be used for meta-analysis and trend-analysis of the design and conduct as well as for results of clinical trials.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
